### ISSUE TITLE
Currently Non-Operational

### ISSUE THREAD

**Issue by koktavy** [DSprtn/GTFO_VR_Plugin#19]
_Being log file: "ISSUE #019"_

Class II Notice of further investigational interest.
Per the creator, this program is classified [//non-operational](https://www.reddit.com/r/GTFO/comments/hil72d/version_08_of_the_gtfo_vr_mod_is_now_out_includes/g9qp3kb/).

Candidates for current non-operational status:
- Most recent executive status **_drop .. # 004_**...
- Subsequent `BepInEx` revisions.

163e4687-e89b-gtff-00-4266141740vr

Please remain posted for creator advisory.

**Comment by SomePsychonaut** [comment]
Is this issue still a thing?

**Comment by cercata** [comment]
> Is this issue still a thing?

Yes, he's working on it as we can see on the readme:

_As of the newest update the game uses a different compiler and the mod will require a significant rewrite to support a new framework. The new version is currently being worked on!_

It's a big change in the game, from Mono to IL2CPP ...

**Comment by cercata** [comment]
GAME OVER :(

He says it's imposible with il2cpp

**Comment by y4my4my4m** [comment]
> GAME OVER :(
> 
> He says it's imposible with il2cpp

https://github.com/BepInEx/BepInEx/releases

BepInEx seems to work with il2cpp though, i assume its the mod that needs a rewrite?

@DSprtn can you provide some clarity on this? Cheers

**Comment by DSprtn** [comment]
Il2CPP brings many limitations with itself. Unity code that doesn't get used by the game gets removed, some methods of applying patches are not possible anymore and injecting MonoBehaviours was broken up until recently (and still is, in some ways), amongst other things.

However, since the modding tools have improved a bunch I've been giving it another try the past week. I already managed to get it pretty close to working again (boot into menu in VR, VR input etc.)

It is definitely much harder and more crash happy but I'll keep you posted. If I get it working I'll have to figure out a way to redistribute it all because I've had to modify unhollower libs and use official Unity libraries for code unstripping. libraries which I'm pretty sure I can't really distribute willy-nilly.

If I get that all figured out the first il2cpp release will probably be missing some features relative to the last mono release due to limitations. Also, once rundown 5 releases it will definitely break again and because there will be no Mono code to decompile it will be much harder to figure out what broke and where. Any changes to methods I'm patching will break the mod again and will be hard to fix.

It looks bleak, but I'm trying anyway ^^

Update: 

Working on one of the last issues - The VR rendering itself which I have narrowed down to RenderTextures not being unstripped correctly. I'm working with/annoying the hell out of Unhollower's creator to get it fixed ^^

**Comment by y4my4my4m** [comment]
@DSprtn
very cool, thanks for the informative response!

I'd love to try it out so, good luck with the continuation on the compatibility issue :)

**Comment by cercata** [comment]
Awesome, there is still hope :)

**Comment by DSprtn** [comment]
It ended up being quite a pain (roughly 25 hours of work), but I did get rendering to work, with some great help from Knah. I'm gonna continue fixing stuff up but I'd say the biggest hurdle has been passed!

**Comment by y4my4my4m** [comment]
@DSprtn wow! thank you so much, looking forward to it

**Comment by cercata** [comment]
>but I'd say the biggest hurdle has been passed!

Awesome !!!!!

**Comment by DSprtn** [comment]
I expect to release it this weekend with no features missing (some new things fixed even!)

Would never believe I'd say this but let's hope R5 isn't right around the corner so I have some time to rest from this madness ^^

As always you can follow the progress in realtime on the Trello page I have listed in the Readme.

**Comment by Mark104** [comment]
Very well done Dsprtn, I know there's a lot of people watching this silently that very much appreciate your work!

**Comment by cercata** [comment]
> Would never believe I'd say this but let's hope R5 isn't right around the corner so I have some time to rest from this madness

I think no change can be that big as the transition to IL2CPP ... You deserve a good rest :)

**Comment by Hoshi82** [comment]
Holy crap. This will be...WOHOO! Thanks for still trying to get it working! Or better get it working again.

**Comment by phunkaeg** [comment]
Oh wow, I was just trying to play this again in VR and the start of this thread had me pretty scared!

Amazing work @DSprtn !

**Comment by AlyxiaFox** [comment]
Thank you for putting in so much work to make this happen @DSprtn, I look forward to your future work~

**Comment by digitalvagrant** [comment]
This is the best news I've heard all week.  I'll definitely be streaming this the moment it comes out.

**Comment by DSprtn** [comment]
New release is out! Enjoy!

**Comment by y4my4my4m** [comment]
@DSprtn just FYI, it worked great. Thank you :)

**Comment by cercata** [comment]
> Would never believe I'd say this but let's hope R5 isn't right around the corner so I have some time to rest from this madness ^^

It looks like they were just waiting for you to publish the update:
https://steamcommunity.com/games/493520/announcements/detail/3102392357031056205
